/**
 * アプリケーション全体で使用するエラーコード定数
 */
export const ErrorCodes = {
  // Database errors
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_SAVE_ERROR: 'DB_SAVE_ERROR',
  DB_FETCH_ERROR: 'DB_FETCH_ERROR',
  DB_UPDATE_ERROR: 'DB_UPDATE_ERROR',
  DB_DELETE_ERROR: 'DB_DELETE_ERROR',
  DB_NOT_FOUND: 'DB_NOT_FOUND',

  // Business logic errors
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  INVALID_NOTIFICATION_TIMING: 'INVALID_NOTIFICATION_TIMING',
  INVALID_SALE_STATUS: 'INVALID_SALE_STATUS',

  // Application layer errors
  USECASE_EXECUTION_FAILED: 'USECASE_EXECUTION_FAILED',
  TICKET_COLLECTION_FAILED: 'TICKET_COLLECTION_FAILED',
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',
  NOTIFICATION_BATCH_FAILED: 'NOTIFICATION_BATCH_FAILED',

  // External service errors
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  LINE_API_ERROR: 'LINE_API_ERROR',
  SCRAPING_ERROR: 'SCRAPING_ERROR',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FIELD_TYPE: 'INVALID_FIELD_TYPE',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
