# Cloud Scheduler Configuration for Monthly Ticket Summary
# This file defines the configuration for monthly ticket summary job

job:
  name: monthly-ticket-summary
  description: Monthly ticket summary for Urawa Reds supporters
  schedule: '0 11 1 * *' # 11:00 UTC = 20:00 JST on 1st day of each month
  timeZone: Asia/Tokyo
  attemptDeadline: 120s # 2 minutes (sufficient for summary generation)

http_target:
  uri: '${CLOUD_RUN_SERVICE_URL}/api/ticket-summary'
  httpMethod: POST
  headers:
    Content-Type: application/json
  body: |
    {
      "source": "cloud-scheduler-monthly",
      "timestamp": "${TIMESTAMP}"
    }

auth:
  serviceAccountEmail: '${SCHEDULER_SERVICE_ACCOUNT}'
  audience: '${CLOUD_RUN_SERVICE_URL}'

retry_config:
  retryCount: 3
  maxRetryDuration: 300s # 5 minutes
  minBackoffDuration: 10s
  maxBackoffDuration: 60s
  maxDoublings: 2
