name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Start Supabase
      run: supabase start

    - name: Create .env file for CI
      run: cp .env.example .env

    - name: Verify formatting
      run: deno fmt --check

    - name: Run linter
      run: deno lint

    - name: Run tests
      run: deno test --allow-env --allow-net=127.0.0.1 --coverage=coverage --env-file .env

    - name: Generate coverage report
      run: deno coverage coverage --lcov --output=coverage.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.lcov
        fail_ci_if_error: false

  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Type check
      run: deno check **/*.ts

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Security audit
      run: |
        # Denoのセキュリティ監査（将来的にdeno auditが利用可能になったら使用）
        echo "Security audit placeholder - implement when deno audit is available"