name: Deploy to Supabase

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Install Supabase CLI
      run: |
        curl -sSfL https://supabase.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify formatting and linting
      run: |
        deno fmt --check
        deno lint

    - name: Run tests
      run: deno test --allow-all

    - name: Type check
      run: deno check **/*.ts

    - name: Login to Supabase
      run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Link to Supabase project
      run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

    - name: Deploy Edge Functions
      run: supabase functions deploy --no-verify-jwt

    - name: Deploy database migrations
      run: supabase db push

    - name: Notification on success
      if: success()
      run: |
        echo "🚀 Deployment successful to production environment"

    - name: Notification on failure
      if: failure()
      run: |
        echo "❌ Deployment failed - check logs for details"